=== Skunksia/bsi2526/zadanie_05/faktura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="faktura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tlo" type="xs:string"/>
        <xs:element name="wiersz" maxOccurs="10">
          <xs:complexType>
            <xs:sequence>
              <xs:attribute name="ID" type="xs:string" use="optional"/>
              <xs:element name="Lp" type="xs:integer"/>
              <xs:element name="nazwa" type="xs:string"/>
              <xs:element name="miara" type="xs:string"/>
              <xs:element name="cena">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1"/>
                    <xs:maxInclusive value="9999"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Skunksia/bsi2526/zadanie_05/faktura.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="faktura.xsl"?>
<faktura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="faktura.xsd">
  <tlo>faktura.jpg</tlo>
  <wiersz ID="w1">
    <Lp>1</Lp>
    <nazwa>Miska</nazwa>
    <miara>szt</miara>
    <cena>123</cena>
  </wiersz>
  <wiersz ID="w2">
    <Lp>2</Lp>
    <nazwa>mÄ…ka</nazwa>
    <miara>kg</miara>
    <cena>2</cena>
  </wiersz>
  <wiersz ID="w3">
    <Lp>3</Lp>
    <nazwa>sok</nazwa>
    <miara>szt</miara>
    <cena>1000</cena>
  </wiersz>
</faktura>
